// AUTO-GENERATED - DO NOT EDIT
// Generated by eniem-cli

export interface GeneratedMeter {
  slug: string;
  name: string;
  polarMeterId: string;
  eventNames: string[];
}

export const sandboxMeters = [
  {
    slug: "llm-tokens",
    name: "LLM Tokens",
    polarMeterId: "d1e2f3a4-5678-9abc-def0-1234567890ab",
    eventNames: ["llm-token-usage"],
  },
] as const satisfies readonly GeneratedMeter[];

export type MeterSlug = (typeof sandboxMeters)[number]["slug"];

export type MeterEventNames<S extends MeterSlug> = Extract<
  (typeof sandboxMeters)[number],
  { slug: S }
>["eventNames"][number];

export function getMeters(
  env: "sandbox" | "production"
): readonly GeneratedMeter[] {
  // Production meters will be added by a subsequent task
  return env === "sandbox" ? sandboxMeters : sandboxMeters;
}

export function getMeter(
  env: "sandbox" | "production",
  slug: MeterSlug
): GeneratedMeter | undefined {
  return getMeters(env).find((m) => m.slug === slug);
}
